config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  get 'carts/show'

  get 'carts/:id' => "carts#show", as: "cart"

  delete 'carts/:id' => "carts#destroy"

  get 'products/search' => "products#search", as: "products_search"

  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"

  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"

  post 'line_items' => "line_items#create"

  get 'line_items/:id' => "line_items#show", as: "line_item"

  delete 'line_items/:id' => "line_items#destroy"

  get 'orders/index'

  get 'orders/show'

  get 'orders/new'

  get 'orders/users/:id' => "orders#show_by_user", as: "orders_by_user"

  get 'orders/users/:id/summary' => "orders#show_summary_by_user", as: "orders_summary_by_user"

  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'users/index'

  get 'users/new'

  get 'users/create'

  get 'pages/secret'

  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create, :custom_action]
  resources :users, only: [:index, :new, :create]
  resources :products
  resources :orders

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  # LOGIC
  def sub_total
    sum = 0
    line_items.each do |line_item|
      sum+= line_item.total_price
    end
    return sum
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  belongs_to :order

  # LOGIC
  def total_price
    self.quantity * self.product.price
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  belongs_to :cart
  belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :current_cart
  helper_method :current_user

  def current_user
    # If session[:user_id] is nil, set it to nil, otherwise find the user by id.
    @current_user ||= session[:user_id] && User.find_by(id: session[:user_id])
  end

  def check_login
    if current_user.blank?
      render plain: '401 Unauthorized', status: :unauthorized
    end
  end

  private
  def   current_cart
    if session[:cart_id]
      cart = Cart.find_by(:id => session[:cart_id])
      if cart.present?
        @current_cart = cart
      else
        session[:cart_id] = nil
      end
    end

    if session[:cart_id] == nil
      @current_cart = Cart.create
      session[:cart_id] = @current_cart.id
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :check_login

  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

  before_action :check_login

  def create
    # Find associated product and current cart
    chosen_product = Product.find(params[:product_id])
    current_cart = @current_cart

    # If cart already has this product then find the relevant line_item and iterate quantity otherwise create a new line_item for this product
    if current_cart.products.include?(chosen_product)
      # Find the line_item with the chosen_product
      @line_item = current_cart.line_items.find_by(:product_id => chosen_product)
      # Iterate the line_item's quantity by one
      @line_item.quantity += 1
    else
      @line_item = LineItem.new
      @line_item.cart = current_cart
      @line_item.quantity = 1
      @line_item.product = chosen_product
    end

    # Save and redirect to cart show path
    @line_item.save
    redirect_to cart_path(current_cart)
  end

  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
    redirect_to cart_path(@current_cart)
  end

  def add_quantity
    @line_item = LineItem.find(params[:id])
    @line_item.quantity += 1
    @line_item.save
    redirect_to cart_path(@current_cart)
  end

  def reduce_quantity
    @line_item = LineItem.find(params[:id])
    if @line_item.quantity > 1
      @line_item.quantity -= 1
    end
    @line_item.save
    redirect_to cart_path(@current_cart)
  end

  private
  def line_item_params
    params.require(:line_item).permit(:quantity,:product_id, :cart_id)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :check_login
  def index
      @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def show_by_user
    @orders = Order.where(:user_id => params[:id])
  end

  def show_summary_by_user

    @items = nil
    @items = Order.where(:user_id => params[:id]) unless params[:id] == 'all'

    @items = Order
               .joins('INNER JOIN line_items ON orders.id = line_items.order_id')
               .joins('INNER JOIN products ON products.id = line_items.product_id')
               .group('line_items.product_id')
               .select("line_items.product_id, products.name, sum(line_items.quantity) as sum_line_items")
               .order("sum_line_items DESC")



  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.user_id = session[:user_id]
    @current_cart.line_items.each do |item|
      @order.line_items << item
      item.cart_id = nil
    end
    @order.save
    Cart.destroy(session[:cart_id])
    session[:cart_id] = nil
    redirect_to root_path
  end

  private
  def order_params
    params.require(:order).permit(:card_no)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # index is a public page
  def index
  end

  # secret is a private page, only logged-in user can enter
  def secret
    if current_user.blank?
      render plain: '401 Unauthorized', status: :unauthorized
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :check_login
  def index
      @products = Product.all
  end

  def search
    @products = Product.where("name LIKE ?", "%#{params[:query]}%")
  end

  def new
    if(@current_user.is_admin)
      @product = Product.new
    else
      render plain: '401 Unauthorized', status: :unauthorized
    end
  end

  def create
    @product = Product.create(product_params)
    redirect_to products_path
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to products_path
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :price)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(name: params[:user][:name])

    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:alert] = "Login failed"
      redirect_to new_user_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :check_login, only: [:index, :show, :update, :destroy]

  def index
      @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path
      flash[:notice] = "User created successfully"
    else
      flash[:alert] = "User not created"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<h2>Cart show</h2>
<ul>
  <% @cart.line_items.each do |line_item| %>
    <li>Item: <%= line_item.product.name %>/ Price: <%= number_to_currency(line_item.product.price) %>/ Quantity: <%= line_item.quantity %>/ Total Price: <%= number_to_currency(line_item.total_price) %>
      <ul>
        <li>
          <%= link_to "Add one", line_item_add_path(:id => line_item), method: :post %>
          <%= link_to "Reduce one", line_item_reduce_path(:id => line_item), method: :post %>
        </li>
        <li>
          <%= link_to "Remove item", line_item_path(line_item), method: :delete %>
        </li>
      </ul>

  <% end %>
</ul>
<h3>Sub total: <%= number_to_currency(@cart.sub_total) %></h3>
<%= link_to "Proceed to checkout", new_order_path %><br>
<%= link_to "Empty cart", cart_path(@current_cart),method: :delete, data: {confirm: "Are you sure?"} %>
<%= link_to "Back", :back %>

app/views/orders/index.html.erb
<h2>All Orders</h2>
<table border="1">
<% @orders.each do |order| %>
  <tr><td>
  <p>User ID: <%= order.user_id %></p>
  <p>Card No: <%= order.card_no %></p>
  <p>Line Items: </p>
  <ul>
    <% order.line_items.each do |item| %>
      <li><%= item.quantity %> x <%= item.product.name %></li>
    <% end %>
  </ul>
  </td></tr>
<% end %>
</table>
<%= link_to "Main Menu", root_path %>

app/views/orders/new.html.erb
<h2>New Order</h2>
<table border="1"><tr><td>
<%= form_for(@order) do |f| %>
<!--  <p>-->
<!--    <%#= f.label :user_id %><br>-->
    <%#= f.number_field :user_id, value: , required: true, autofocus: true, readonly: true %>
<!--  </p>-->
  <p>
    <%= f.label :card_no %><br>
    <%= f.text_area :card_no %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
</td></tr></table>
<%= link_to "Main Menu", root_path %>

app/views/orders/show.html.erb
<h2>Order details</h2>
<table border="1">
  <% if @order %>
    <tr><td>
  <p>User ID: <%= @order.user_id %></p>
  <p>Card No: <%= @order.card_no %></p>
  <p>Line Items: </p>
  <ul>
    <% @order.line_items.each do |item| %>
      <li><%= item.quantity %> x <%= item.product.name %></li>
    <% end %>
  </ul>
    </td></tr>
<% end %>
</table>
<%= link_to "Main Menu", root_path %>

app/views/orders/show_by_user.html.erb
<h2>All Orders By User</h2>
<table border="1">
  <% @orders.each do |order| %>
  <tr>
  <td>
  <p>Order ID: <%= order.id %></p>
  <p>User ID: <%= order.user_id %></p>
  <p>Card No: <%= order.card_no %></p>
  <p>Line Items: </p>
  <ul>
    <% order.line_items.each do |item| %>
      <li><%= item.quantity %> x <%= item.product.name %></li>
    <% end %>
  </ul>
  <% end %>
  </td>
  </tr>
</table>
<%= link_to "Main Menu", root_path %>

app/views/orders/show_summary_by_user.erb
<h2>Top Ordered Items</h2>
<table border="1">
<% @items.each do |item| %>
    <tr>
    <td>
  <p>Product: <%= item.product_id %>:<%= item.name %></p>
  <p>Total Order Qty: <%= item.sum_line_items %></p>
    </td>
    </tr>
<%end %>
</table>
<%= link_to "Main Menu", root_path %>

app/views/products/edit.html.erb
<%= form_for(@product) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, required: true, autofocus: true, placeholder: "Enter product name" %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.number_field :price, required: true %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to "Back", products_path %><br>

app/views/products/index.html.erb
<h2>All Products</h2>

<% @products.each do |product| %>
  <p>Name: <%= product.name %>; unit price of <%= number_to_currency(product.price) %></p>
  <p>
    <%= link_to "Edit", edit_product_path(product) %> |
    <%= link_to "Delete", product_path(product), method: :delete, data: {confirm: "Are you sure?"} %>
    <%= button_to "Add #{product.name} to cart", line_items_path(:product_id => product.id) %>
  </p>
<% end%>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<h2>New Product</h2>
<table border="1">
  <tr><td>
<%= form_for(@product) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, required: true, autofocus: true, placeholder: "Enter product name" %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.number_field :price, required: true %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to "Back", products_path %><br>
  </td></tr>
</table>

app/views/products/search.html.erb
<h2>Search Results</h2>
<table border="1">

<% @products.each do |product| %>
    <tr><td>
      <p>Name: <%= product.name %>; unit price of <%= number_to_currency(product.price) %></p>
  <p>
    <%= link_to "Edit", edit_product_path(product) %> |
    <%= link_to "Delete", product_path(product), method: :delete, data: {confirm: "Are you sure?"} %>
    <%= button_to "Add #{product.name} to cart", line_items_path(:product_id => product.id) %>
  </p>
    </td></tr>
<% end%>
</table>
<%= link_to "Back to all products", products_path %><br>
<%= link_to "Main Menu", root_path %>

app/views/user_sessions/create.html.erb
<h2>UserSessions#create</h2>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/new.html.erb
<h2>Login page</h2>
<table><tr></tr></table>
<%#= form_for(@product) do |f| %>
<%= form_for @user, url: user_sessions_path do |f| %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <p>
    <%= f.submit 'Login' %>
  </p>
<% end %>

app/views/users/create.html.erb
<h2>Users#create</h2>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h2>All User details</h2>
<table border="1">
  <thead>
  <tr>
    <th>id</th>
    <th>name</th>
    <th>is_admin</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.name %></td>
      <td><%= user.is_admin %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'New User', new_user_path %>
<%= link_to "Back", :back %>

app/views/users/new.html.erb
<h2>New User</h2>
<table border="1">
  <tr><td>
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
<!--    <%#= f.label "is_admin" %> <br />-->
<!--    <%#= f.check_box :is_admin, {}, true, false %> <br />-->
    <%= f.label :is_admin %><br>
    <%= f.text_field :is_admin %>
  </div>
  <p>
    <%= f.submit %>
  </p>
<% end %>
</td></tr>
</table>
<%= link_to "Back", :back %>